INSERT INTO USUARIO(nome, email, senha) VALUES('Adm', 'adm@email.com', '$2a$10$sFKmbxbG4ryhwPNx/l3pgOJSt.fW1z6YcUnuE2X8APA/Z3NI/oSpq');
INSERT INTO USUARIO(nome, email, senha) VALUES('Aluno', 'aluno@email.com', '$2a$10$sFKmbxbG4ryhwPNx/l3pgOJSt.fW1z6YcUnuE2X8APA/Z3NI/oSpq');

INSERT INTO PERFIL(ID,NOME) VALUES(1,'ROLE_ALUNO');
INSERT INTO PERFIL(ID,NOME) VALUES(2,'ROLE_ADMINISTRADOR');

/*INSERT INTO USUARIO_PERFIS(USER_ID,PERFIS_ID) VALUES(1,2);
INSERT INTO USUARIO_PERFIS(USER_ID,PERFIS_ID) VALUES(2,1);
*/


